### ISSUE TITLE
Reset.css causing bug

### ISSUE THREAD

**Issue by franklinjavier** [sudomf/remix-vite#10]
### Description

Fala Mayke, parabéns pela iniciativa. 

Here is the minimal repo to reproduce the issue https://github.com/franklinjavier/remix-vite-resetcss-bug

### Library version

0.1.5

### Node version

16.18.1

**Comment by sudomf** [comment]
Obrigado @franklinjavier.

I'll take a look ASAP.

**Comment by sudomf** [comment]
@franklinjavier can you please test it with remix-vite 0.2.4?

**Comment by franklinjavier** [comment]
It worked... thank you!

**Comment by franklinjavier** [comment]
https://github.com/franklinjavier/remix-vite-resetcss-bug/commit/58d177bc2e8fd4ec905b78b44f0ea8a5cccdcf42

**Comment by sudomf** [comment]
> It worked... thank you!

No problem. Take care.
