### ISSUE TITLE
Exported variable being removed from browser build

### ISSUE THREAD

**Issue by jrestall** [sudomf/remix-vite#12]
### Description

I have a route module that both uses and exports a zod validator. It exports the validator variable for use in unit tests and defines it in the route file for use in the default component and action.

```ts
export const validator = withZod(
  z.object({
    username: z.string().min(1, { message: "Username is required" })
    password: z.string().min(1, { message: "Password is required" }),
  })
);

export async function action({ request }: ActionArgs) {
  const result = await validator.validate(await request.formData());
  ...

export default function Login() {
  return (
      <Form validator={validator} method="post">
        ...
```
However the route fails to load due to the validator variable not existing in the browser build. Likely due to [this](https://github.com/sudomf/remix-vite/blob/ddb22f4c9b5723c4944f055a86391ced65151686/src/plugins/transform.ts#L29) code that strips any unrecognized export from the build.

Maybe we could reverse the logic and only exclude known server exports rather than excluding everything or somehow match Remix's tree-shaking approach? 

### Library version

0.2.2

### Node version

v16.17.1

**Comment by sudomf** [comment]
Hey @jrestall . Thanks for submitting the issue.

Can you please test it with the new remix-vite version 0.2.3?

**Comment by jrestall** [comment]
Working now, thanks so much @sudomf!

**Comment by sudomf** [comment]
No problem. Take care
