### ISSUE TITLE
checkVersion fails behind a corporate proxy

### ISSUE THREAD

**Issue by rliang** [sudomf/remix-vite#19]
### Description

When I run remix-vite I get

`FetchError: request to https://registry.npmjs.org/remix-vite failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org`

A solution to this could be in adding a `--no-check-version` flag?

### Library version

0.2.5

### Node version

16

**Comment by sudomf** [comment]
Hey @rliang. The solution will be released soon. On version 0.3.0.
