### ISSUE TITLE
Adding plugins?

### ISSUE THREAD

**Issue by rafcontreras** [sudomf/remix-vite#4]
### Description

I'm not very experienced to Vite, but it looks like it works with plugins as middlewares

### Why

I'd like to use socket.io with Remix Vite

### Alternatives

None

**Comment by sudomf** [comment]
Hey @rafcontreras. Remix Vite is meant to be just a dev server, not a production bundler. So, we can expose plugins support for Vite. But it will work just for development time.

**Comment by sudomf** [comment]
Closing as remix-vite is not meant to replace the Remix compile ecosystem. But just act as dev-server.
