### ISSUE TITLE
GET request triggered with Tailwind CSS content in the URL

### ISSUE THREAD

**Issue by shripadk** [sudomf/remix-vite#7]
### Description

For some weird reason a GET request is initiated from the browser on every page load with following route path:

```
No routes matched location "/*!%20tailwindcss%20v3.2.2%20%7C%20MIT%20License%20%7C%20
https://tailwindcss.com*//*1.%20Prevent%20padding%20and%20border%20from%20affecting%20element%20width.%20
(https://github.com/mozdevs/cssremedy/issues/4)2.%20Allow%20adding%20a%20border%20to%20an%20element%20
by%20just%20adding%20a%20border-width.%20
(https://github.com/tailwindcss/tailwindcss/pull/116)*/*,::before,::after%20%7B%20%20box-sizing:%20
border-box;%20%20/*%201%20*/%20%20border-width:%200;%20%20/*%202%20*/%20%20
border-style:%20solid;%20%20/*%202%20*/%20%20border-color:%20"
```

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/189344/200749852-021667c6-0a92-493e-9d23-ab078f6d9915.png">

and browser logs:

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/189344/200751053-1791129a-cfa5-4a97-b1ff-4bf1a9f1a5bf.png">

Not sure what is triggering it.

### Library version

0.1.5

### Node version

v16.14.1

**Comment by jrestall** [comment]
Fix for me was to add ?url to the end of the tailwind stylesheet import to explicitly import it as a url rather than content. As shown [here](https://github.com/sudomf/remix-vite/blob/6dffc68a95c482506545d62821bdcc063adf3426/example/app/root.tsx#L11) and documented in vite [here](https://vitejs.dev/guide/assets.html#explicit-url-imports).

**Comment by shripadk** [comment]
@jrestall I did not know this. Thank you!

**Comment by fergusmeiklejohn** [comment]
Sadly this solution is not complete because tagging `?url` on the end of the CSS import breaks the Remix build. It can no longer find the module: `Error: Cannot find module '~/styles/tailwind.css?url'`

**Comment by shripadk** [comment]
@fergusmeiklejohn Weird. I don't have this issue. Do you have a reproducible repo I can try?

**Comment by jrestall** [comment]
@fergusmeiklejohn I can't reproduce your error immediately either, running remix build on this repos example project seems to work okay for me.

**Comment by fergusmeiklejohn** [comment]
yeah it's weird.. sorry @shripadk it's a private repo, I'll see if I can recreate in a public repo
these are the errors I get when using `?url` syntax[](url)
<img width="999" alt="CleanShot 2022-11-10 at 09 49 59@2x" src="https://user-images.githubusercontent.com/11864025/200981226-811c98e4-7d1c-4955-b382-82a16dbb654d.png">
<img width="829" alt="CleanShot 2022-11-10 at 09 51 09@2x" src="https://user-images.githubusercontent.com/11864025/200981232-ebdbcfc7-faf1-4b23-b608-6a21be3d86d6.png">

**Comment by fergusmeiklejohn** [comment]
The really peculiar thing is that it all worked fine with tailwind and no `?url` when I set it up with a simple vanilla Remix app. It's when I tried to set it up with a complex app like this one that it wouldn't work

**Comment by shripadk** [comment]
> I'll see if I can recreate in a public repo

@fergusmeiklejohn yes it'll be great if you could setup one. Will check it out!
